version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    environment:
      - OURCHAT_SERVER_HOST=0.0.0.0
      - OURCHAT_SERVER_PORT=8080
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped