version: '3'

services:
  ourchat:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/templates:/app/templates
      - ./backend/static:/app/static
    environment:
      - OURCHAT_SERVER_HOST=0.0.0.0
      - OURCHAT_SERVER_PORT=8080
    restart: unless-stopped